### ISSUE TITLE
Support JVM intrinsics

### ISSUE THREAD

**Issue by thomasdarimont** [AdoptOpenJDK/jitwatch#169]
It would be cool if jitwatch would highlight JVM intrinsics like String.indexOf(..) in the Java code viewer and /or could suggest the appropriate intrinsic version of a method if appropriate.

This information could help tuning the code.

Could involve parsing the appropriate header files like:
http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/classfile/vmSymbols.hpp#l614

**Comment by chriswhocodes** [comment]
Hi Thomas,

Use of intrinsics is present in the production VM hotspot.log and is visualised in the bytecode pane of the TriView screen. I think I will introduce a set of icons in the margin to make the line highlighting more intuitive.

I could quite easily add highlighting to the source pane as long as the LineNumberTable bytecode-to-source mappings are present in the class file (JITWatch breaks pretty badly if they are stripped out).

Suggesting an intrinsic where one is not currently used sounds tricky? It might be possible if there are overloaded methods (same name) and only one is backed by an instrinsic?

Otherwise I think we're into trying to parse the intent of the source code?

Some to discuss at JCrete?

Cheers,

Chris

**Comment by thomasdarimont** [comment]
Sounds good.

wrt. to suggesting the intrinsics - yes I meant only suggesting intrinsics that are overloads of the current methods - maybe it is more of a hint than a suggestion in the sense of "hey you are using x(a,b) but there is a JVM intrinsic for the variant x(a) is it possible to change your algorithm?"

:+1: for JCrete :)

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
