### ISSUE TITLE
Runtime-generated classes not shown?

### ISSUE THREAD

**Issue by rvansa** [AdoptOpenJDK/jitwatch#194]
I am generating some classes in runtime using javassist, but I can't see those in JITWatch. I can even confirm that these are loaded and compiled from the log:
`[Loaded org.infinispan.interceptors.EntryWrappingInterceptor$Opt2 from __JVM_DefineClass__]`

```
Decoding compiled method 0x00007fde65536f90:
Code:
[Entry Point]
[Constants]
  # {method} {0x00007fde251d03d0} 'AbstractLockingInterceptor$lockAndRecord' '(Lorg/infinispan/context/InvocationContext;Ljava/lang/Object;J)V' in 'org/infinispan/interceptors/locking/NonTransactionalLockingInterceptor$Opt6'
```
(disassembly follows)

Is this expected/desired? Is there a way to expose them currently, or should I dump the classes and replace the `__JVM_DefineClass__` with the dumped location before loading the log?
I've seen missing classes when I've generated the log on one machine and opened it on another, so I guess the location is important for JITWatch, right?

**Comment by chriswhocodes** [comment]
Hi,
At the moment JITWatch does need access to the class files. It can load them from a folder or a zip/jar and this can either be explicitly set in the config or it can try and find them via the TraceClassLoading log statements.
Dumping the classes to the filesystem and pointing to that location in the config is the quickest fix. Longer term I can evaluate how much can be inferred from the logs instead of relying on the class files.
Thanks,
Chris

**Comment by rvansa** [comment]
OK, closing (and sorry to use GH issues as support forum, but I haven't seen any links to forum).

**Comment by chriswhocodes** [comment]
https://groups.google.com/forum/#!forum/jitwatch :)

**Comment by headius** [comment]
Nearly ten years later and it seems like this still doesn't work? I wonder if we can revisit this given the amount of generated code in a typical JVM application now (dynamic languages like JRuby, invokedynamic call sites and LambdaForm method handles, string concatenation, etc).

In my case, I'm actually not that interested in the bytecode... I want to be able to use JITWatch to browse Ruby methods that have been jitted through bytecode to native. We do generate bytecode lazily for hot methods, but only at runtime.

Sorry for not posting to forum but it seems dead since 2018. I'm also happy to take suggestions for alternative tools.
