### ISSUE TITLE
The prebuilt jar link is broken

### ISSUE THREAD

**Issue by theagentd** [AdoptOpenJDK/jitwatch#209]
Hello.

The prebuilt jar link (https://adopt-openjdk.ci.cloudbees.com/job/jitwatch/) just gives a 404 right now.

**Comment by chriswhocodes** [comment]
Thanks, updated: https://github.com/AdoptOpenJDK/jitwatch/wiki

**Comment by theagentd** [comment]
I'm probably just stupid, but I can't find a download link there... It just gives information about how the build procedure went...

**Comment by chriswhocodes** [comment]
Hi, if it's not clear then that's something I need to improve :)

There are a few ways to run JITWatch:

If you want to use it as a library in another project you can add the maven dependency to your own project's pom file:

```xml
  <dependencies>
    <dependency>
      <groupId>com.chrisnewland</groupId>
      <artifactId>jitwatch</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
```

Or you can clone the project from GitHub using:
```bash
git clone https://github.com/AdoptOpenJDK/jitwatch.git
```
and then build and run it using either ant:
```bash
ant clean compile run
```
or maven:
```bash
mvn clean compile exec:java
```
or gradle (currently not working due to some refactoring):
```bash
./gradlew
```
There is no single jar that you can execute java -jar with. This is mainly due to the dependency on tools.jar which is part of the JDK but not on the standard JRE classpath.

Hope that helps?
