### ISSUE TITLE
Assert not null: memberBytecode

### ISSUE THREAD

**Issue by snOm3ad** [AdoptOpenJDK/jitwatch#263]
Hello I was trying to install the program using maven clean install. Everything went perfectly fine it downloaded all dependencies and started executing the JUnit tests right away. It was going pretty good till it hit test run 18! This is when two failures occurred, the following is the stack trace printed by maven.
```java
java.lang.AssertionError
	at org.adoptopenjdk.jitwatch.test.TestBytecodeLoader.doTestOverloadedMethod(TestBytecodeLoader.java:805)
	at org.adoptopenjdk.jitwatch.test.TestBytecodeLoader.testExampleOverloadedMethodObject(TestBytecodeLoader.java:823)
```
I checked the project files and, the problem seems to happen when the function `testExampleOverloadedMethodString()` performs a call to `doTestOverloadedMethod()` with `java.lang.String.class` as a parameter. The error occurs in the body of `doTestOverloadedMethod()` on line 805 where there is a call to an `assertNotNull()` function. The parameter the function is receiving is an instance of the `MemberByteCode` class which is created in line 803.

I am using OS-X Yosemite. Let me know if there is anything else you need to know.

**Comment by chriswhocodes** [comment]
Hi, thanks for the report.

Please can you let me know what Java version you are running? e.g. JDK8 update 144

Can you also check you've fetched the latest version of JITWatch from GitHub? I seem to recall fixing this bug before but it's possible I didn't fix it for all platforms.

Thanks,

Chris

**Comment by snOm3ad** [comment]
Hello Chris,

My Java version is JDK8 141 and my Maven version is 3.5. The JITWatch version is the latest version that is posted on Github i.e. 1.1.6 let me know if there's anything else you need to know.

**Comment by chriswhocodes** [comment]
Hi,

I remember now, this method caused me lots of problems when running under my Jenkins CI build.

I can get it to execute correctly on my own OSX Yosemite, JDK8u144 and maven 3.5 but this test seems very sensitive to execution environment as it attempts to locate and load its own class file from the filesystem (as a binary blob not using a classloader).

If you can think of a way to make this test more robust I'd really appreciate it, otherwise I'd suggest you ignore this test until I can find time to fix it.

Thanks,

Chris

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
