### ISSUE TITLE
Is it possible to make jarScan more verbose?

### ISSUE THREAD

**Issue by zsokolowski** [AdoptOpenJDK/jitwatch#279]
Hi I'm waiting for report for prolonged time and I'm not sure what is going on. Is there possibility to make it more verbose?

**Comment by chriswhocodes** [comment]
Hi,
Are you using Java 8 or Java 9?
If you are using Java 8 then JarScan will use the API form of javap (com.sun.tools.javap.JavapTask). This is not available in Java 9 (due to modularisation changes) so JarScan has to repeatedly invoke the javap binary using a ProcessBuilder which is *much* slower :(

I've deliberately not added any status output to JarScan so that it's entire output (CSV format) can be piped into another tool.

Can I ask what size is the jar file / folder you are scanning?

Cheers,

Chris

**Comment by zsokolowski** [comment]
Hi Chris, thanks for the answer. Java 8 latest build 162 AFAIK. Jar is about 5.6 MB. Maybe another output could be possible with the certain flag? And indication that process is progressing. I used Cpu time used by the Windows. However I wasn't sure if proceses is advancing at all. 

Cheers, 
Zbigniew

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/66a3309efa2c35aff963882166fc9d7a3739e902

Use the --verbose switch to print progress info to stderr
e.g.
`./jarScan.sh --verbose --mode=MaxMethodSize --limit=325 /home/chris/java/jre/lib/rt.jar`
