### ISSUE TITLE
+PrintAssembly without compiling for JDK 10 / Linux

### ISSUE THREAD

**Issue by stefan-reich** [AdoptOpenJDK/jitwatch#285]
Hi,

thanks for your work and so on. However: Sorry, I don't accept being forced to "compile libraries myself"... it never works well and it's just ridiculous.

(Yes, insult and ridicule me, computer scientists, but it's like that: I'm on the side of the users - I want it easy. And I'm right in that.)

`apt-get install openjdk-8-jdk` gives me a working (older) JDK with a working +PrintAssembly option.

How can I get the same for an Oracle JDK 10 downloaded manually? It doesn't ship with +PrintAssembly (why not?).

This is for Peppermint Linux 8 (64 Bit) on Intel.

Cheers

PS: [Awesome operating system in Java](http://BotCompany.de)

**Comment by chriswhocodes** [comment]
Hi :)
To use PrintAssembly you need a JDK with the hsdis binary installed for your OS (dll / so / dylib). It looks like your OpenJDK8 build includes this but the Oracle JDK10 does not.

Previously it wasn't possible to distribute hsdis binaries due to license restrictions but I've recently learned that it has been re-licensed so I I'm going to see if it's possible for me to distribute it with JITWatch.
Cheers,
Chris

**Comment by chriswhocodes** [comment]
Sorry, it looks like hsdis will not distributed as a binary with OpenJDK anytime soon.
